fix: correct composite action for creating issues
sigstore/sigstore-probers pull request #82
Opened 2023-06-30 09:00 UTC by yrobla

#### Summary

The action needed to clone the repo on an independent directory to be able to consume it, and some minor tweaks

#### Release Note

NONE

#### Documentation

NONE

2023-06-30 09:03 UTC, JAORMX approved these changes

2023-06-30 20:56 UTC, haydentherapper approved these changes

2023-07-01 09:19 UTC, cpanato commented on .github/actions/create-issue/action.yaml
> +      uses: actions/checkout@v3
```suggestion
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
```

2023-07-01 09:19 UTC, cpanato requested changes
small nit

2023-07-03 07:14 UTC, closed without merging

2023-07-03 16:20 UTC, haydentherapper commented
FYI this was closed

2023-07-10 21:13 UTC, haydentherapper commented
@yrobla Can this be reopened?

2023-07-11 06:36 UTC, yrobla commented
sorry, i deleted because i had conflicts in the repo, and removed it, as i was doing a lot of local testing. I will create a new PR